from PIL import Image
import os
import time
from pygame import mixer
import pyttsx3
from termcolor import colored
engine=pyttsx3.init()
voices = engine.getProperty('voices')
rate = engine.getProperty('rate')
engine.setProperty('rate', 145)


def start(inv):
	time.sleep(1)
	print(colored("\nYou are in front of the house. What do you want to do??",'green'))
	time.sleep(2)
	print(colored("\n1.Open the door",'yellow'))
	time.sleep(1)
	print(colored("2.Examine the mailbox",'yellow'))
	time.sleep(1)
	print(colored("3. Look under the mat",'yellow'))
	time.sleep(1)
	print(colored("4.Break and look through the window",'yellow'))

	selectionlist = ['1','2','3','4']
	choice = selectchoice(selectionlist)

	if choice =='1':
		print('Trying to open the door....')
		time.sleep(2)
		if 'key' in inv:
			os.system('clear')
			mixer.init()
			mixer.music.load('/home/mehul/Desktop/voices/doorclose.mp3')
			mixer.music.play()
			time.sleep(3)
			print(colored("Yes!! this key opens the door ",'blue'))
			inside(inv)
		else:
			os.system('clear')
			mixer.init()
			mixer.music.load('/home/mehul/Desktop/voices/doorknob.mp3')
			mixer.music.play()
			time.sleep(3)
			print(colored("OOPS ..The door is closed. You'll need a key.",'red'))
			engine.say('OOPS   The door is closed. You ll need a key.')
			engine.runAndWait()
			time.sleep(2) 
			start(inv)
	elif choice == '2':
		os.system('clear')
		mixer.init()
		mixer.music.load('/home/mehul/Desktop/voices/Door.mp3')
		mixer.music.play()
		time.sleep(4)
		print(colored("You opened the mailbox and there is a harddisk",'blue'))
		engine.say('You opened the mailbox and there is a harddisk')
		engine.runAndWait()
		time.sleep(1)
		print("What do you want to do??")
		engine.say('What do you want to do')
		engine.runAndWait()
		time.sleep(1)
		print(colored("\n1. Take the harddisk ",'yellow'))
		time.sleep(0.5)
		print(colored("2. Close the mailbox",'yellow'))
		time.sleep(0.5)		

		selectionlist = ['1','2']
		choice = selectchoice(selectionlist)
		if choice == '1':
			inv.append('harddisk')
			print(colored("\nYou got the harddisk ",'blue'))
			engine.say('You got the harddisk')
			engine.runAndWait()	
			mixer.init()
			mixer.music.load('/home/mehul/Desktop/voices/Door.mp3')
			mixer.music.play()
			time.sleep(3)
			start(inv)
		elif choice =='2':
			mixer.init()
			mixer.music.load('/home/mehul/Desktop/voices/Door.mp3')
			mixer.music.play()
			time.sleep(3)
			print(colored("\nYou closed the mailbox",'red'))
			time.sleep(2)
			start(inv)
	elif choice =='3':
		os.system('clear')
		mixer.init()
		mixer.music.load('/home/mehul/Desktop/voices/mat.mp3')
		mixer.music.play()
		time.sleep(3)
		print(colored("\nThere is a key under the mat",'blue'))
		engine.say('There is a key under the mat')
		engine.runAndWait()	
		time.sleep(1)
		print("What do you want to do??")
		engine.say('what do you want to do')
		engine.runAndWait()
		print(colored("\n1. Take the key ",'yellow'))
		time.sleep(0.5)
		print(colored("2. Put the mat back",'yellow'))
		time.sleep(0.5)

		selectionlist = ['1','2']
		choice = selectchoice(selectionlist)
		if choice =='1':
			inv.append("key")
			print(colored("\nYou got the key ",'blue'))
			engine.say('You got the key')
			engine.runAndWait()
			mixer.init()
			mixer.music.load('/home/mehul/Desktop/voices/tone.mp3')
			mixer.music.play()
			time.sleep(4)
			start(inv)
		elif choice == '2':
			mixer.init()
			mixer.music.load('/home/mehul/Desktop/voices/mat.mp3')
			mixer.music.play()
			time.sleep(2)
			print(colored("\nYou put the mat back",'red'))
			time.sleep(2)
			start(inv)
	elif choice == '4':
		os.system('clear')
		mixer.init()
		mixer.music.load('/home/mehul/Desktop/voices/break.mp3')
		mixer.music.play()
		time.sleep(7)
		print(colored("\nAs you look through the window you see that no one is inside",'yellow'))
		time.sleep(2)
		print(colored("You see a computer on a desk and a door which might lead u to your treasure",'yellow'))
		engine.say('As you look through the window you see that no one is inside     n  a computer on a desk and a door which might lead u to your treasure')
		engine.runAndWait()	
		time.sleep(2)
		start(inv)

def inside(inv):
	print(colored("\nYes you are inside the house now!!\n\n",'blue'))
	engine.say('Yes you are inside the house now ')
	engine.runAndWait()
	time.sleep(1)
	img=Image.open('/home/mehul/Desktop/voices/door.jpg')
	img.show()
	print(colored("There it is.... the door which can make you a millionaire!!!",'green'))
	print(colored("let's go\n",'green'))
	engine.say('  There  it  is    the door  which  can  make  you  a   millionaire ')
	engine.runAndWait() 
	time.sleep(0.5)
	engine.say('lets go')
	engine.runAndWait()   
	mixer.init()
	mixer.music.load('/home/mehul/Desktop/voices/footsteps.mp3')
	mixer.music.play()
	time.sleep(7)
	print('Trying to open the door...\n\n')
	mixer.init()
	mixer.music.load('/home/mehul/Desktop/voices/doorknob.mp3')
	mixer.music.play()
	time.sleep(3)
	time.sleep(2)
	print(colored("OOPS.. door requires a code\n\n",'red'))
	engine.say('OOPS   door requires a code')
	engine.runAndWait()	
	time.sleep(1)
	print('What do you want to do??')
	engine.say('what do you want to do')
	engine.runAndWait()
	time.sleep(1)
	print(colored("\n1.Switch on the computer",'yellow'))
	time.sleep(0.5)
	print(colored("2. Leave the house",'yellow'))
	time.sleep(0.5)
	
	selectionlist = ['1','2']
	choice = selectchoice(selectionlist)

	if choice == '1':
		if 'harddisk' in inv:
			mixer.init()
			mixer.music.load('/home/mehul/Desktop/voices/Keyboard.mp3')
			mixer.music.play()
			time.sleep(3)
			print(colored("\n The computer is booting",'blue'))
			time.sleep(2)
			print(colored("CONGRATS!! You got the code",'blue'))
			engine.say('CONGRATS  You got the code')
			engine.runAndWait()	
			print(colored("\n\nLet's open the door...",'green'))
			mixer.init()
			mixer.music.load('/home/mehul/Desktop/voices/doorclose.mp3')
			mixer.music.play()
			time.sleep(4)
			mixer.init()
			mixer.music.load('/home/mehul/Desktop/voices/win.mp3')
			mixer.music.play()
			time.sleep(3)
			print(colored("\n\nCONGRATS  !! You got the treasure\nCollect and become a MILLIONAIRE...\n\n\n",'cyan'))
			img=Image.open('/home/mehul/Desktop/voices/3.jpg')
			img.show()
			engine.say('CONGRATS You got the treasure Collect and become a MILLIONAIRE...')
			engine.runAndWait()	
			time.sleep(3)
			print(colored(".....for more such amazing games do visit CieLSpieL.com",'magenta'))
			engine.say('for more such amazing games do visit CieLSpieL.com')
			engine.runAndWait()	
			exit(0)
		else:
			print(colored("The computer is not booting, u need to get the harddisk \n\n which u'll get outside the house\n let's take u there",'red'))
			engine.say('The computer is not booting, u need to get the harddisk \n\n which u will get outside the house\n lets take u there')
			engine.runAndWait()	
			time.sleep(2)
			start(inv)
	elif choice == '2':
		os.system('clear')
		mixer.init()
		mixer.music.load('/home/mehul/Desktop/voices/doorclose.mp3')
		mixer.music.play()
		time.sleep(3)
		print('\n You leave the house.')
		time.sleep(2)
		start(inv)

def selectchoice(selectionlist):
	choice = input('\nChoose one of the above options:')
	if choice in selectionlist:
		return choice
	elif choice == 'quit':
		exit(0)
	else:
		print('Invalid input')
		return selectchoice(selectionlist)


img=Image.open('/home/mehul/Desktop/voices/unnamed.png')
img.show()
os.system('clear')
print(colored("Welcome",'red'))
engine.say('Welcome')
engine.runAndWait()
time.sleep(1)
print(colored("        CieL SpieL presents",'blue'))
engine.say('       CieL SpieL presents')
engine.runAndWait()
time.sleep(1.5)
print(colored("                        Treasure Hunt\n\n\n",'yellow'))
engine.say('                          Treasure Hunt')
engine.runAndWait()
time.sleep(2)
i=input("Start the game???(Y/N)")
while True:
	if i=="Y":
		inv=[]
		img=Image.open('/home/mehul/Desktop/voices/screen2.jpg')
		img.show()
		engine.say('There is a treasure inside the house   strive for the way inside using your wits')
		engine.runAndWait()	
		time.sleep(2)
		start(inv)	
	elif i=="N":
		exit(0)
	else:
		print("Enter one of the options(Y/N):",'blue')
		i=input("Start the game???(Y/N)")
